include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    avoid_relative_lib_imports: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    directives_ordering: true
    use_super_parameters: true
    use_key_in_widget_constructors: true
    eol_at_end_of_file: true

dart_code_metrics:
  metrics-exclude:
    - test/**
  extends:
    - package:dart_code_metrics_presets/metrics_recommended.yaml
    - package:dart_code_metrics_presets/pub.yaml
    - package:dart_code_metrics_presets/fake_async.yaml
    - package:dart_code_metrics_presets/get_it.yaml
    - package:dart_code_metrics_presets/intl.yaml
    - package:dart_code_metrics_presets/bloc.yaml
    - package:dart_code_metrics_presets/provider.yaml
    - package:dart_code_metrics_presets/equatable.yaml
  rules:
    - avoid-cubits: false
    - prefer-number-format: false
    - avoid-read-inside-build: false
    - check-is-not-closed-after-async-gap: false
  pubspec-rules:
    - avoid-any-version: false
    - prefer-caret-version-syntax: false
