name: ya_summary
description: "Пересказ статей с помощью YandexGPT"
version: 0.0.1
homepage:

environment:
  flutter: ">=3.22.0"
  sdk: ">=3.5.3 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
