name: ya_summary
resolution: workspace
description: Dart API client for Yandex article summaries
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.11.0

dependencies:
  dio: ^5.11.0
  equatable: ^2.1.0

dev_dependencies:
  test: ^1.27.0
