name: flutter_highlight
resolution: workspace
description: Syntax highlighting widget for Flutter with lots of languages and themes support.
publish_to: none
version: 0.7.1
homepage: https://github.com/git-touch/highlight

environment:
  flutter: ">=3.22.0"
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.2.0
  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
# dependency_overrides:
#   highlight:
#     path: ../highlight
