name: flutter_highlight
description: Syntax highlighting widget for Flutter with lots of languages and themes support.
version: 0.7.1
homepage: https://github.com/git-touch/highlight

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
# dependency_overrides:
#   highlight:
#     path: ../highlight
